const collection = {
  PRODUCT_COLLECTION: 'products',
  PRODUCT_TEMPLATE:'productTemplate',
  USER_COLLECTION: 'users',
  ADMIN_COLLECTION: 'admin',
  CATEGORY_COLLECTION: 'categories',
  ADDRESS_COLLECTION: 'address',
  CART_COLLECTION: 'cart',
  ORDER_COLLECTION: 'orders',
  ORDER_SATUS: 'orderStatus',
  WALLET: 'wallet',
  GUEST_USERS: 'guestusers',
  SUB_CATEGORIES: 'subcategories',
  COUPON_TEMPLATE: 'coupontemplate',
  COUPONS:'coupons',
  VISITORS:'visitors',
  PRODUCT_RATING:'ratings',
  COLORS:'colors',
  SIZES:'sizes',
}
export default collection
